# docker-compose.yml
version: '3.8'

services:
  db:
    image: ankane/pgvector
    container_name: rag_pg_hf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ragdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: rag_app_hf
    ports:
      - "8000:8000"
    environment:
      DB_DSN: postgresql+asyncpg://postgres:password@db:5432/ragdb
    depends_on:
      - db
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
